# Generated by Django 2.2.16 on 2021-03-29 21:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0002_phoneareacode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('abbreviation', models.CharField(blank=True, max_length=128, null=True)),
                ('bounds', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('center', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.AlterField(
            model_name='postalcode',
            name='country',
            field=models.CharField(default='us', max_length=2),
        ),
        migrations.AlterField(
            model_name='province',
            name='country',
            field=models.CharField(default='us', max_length=2),
        ),
    ]
